spring:
  config:
    import: classpath:application-secret.yml

  datasource:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

midas:
  crypto-assets:
    - X:ETHUSD
    - X:REQUSD
#    - ADA
  #Replace with DB pull later
  stock-assets:
    - AVTX
    - MRAI
    - DRCT
  urls:
    polygonUrl: /v2/aggs/ticker/